name: Create PR from feature branches
on:
  push:
    branches:
      - 'feature/**'
      - develop
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Test
      run: echo "${BRANCH_NAME}"

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch
      # - uses: actions/checkout@v2
      #   with:
      #     ref: develop
      # - name: Reset feature branch
      #   run: |
      #     git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
      #     git reset --hard ${{ steps.extract_branch.outputs.branch }}
      # - name: Create Pull Request
      #   uses: CalefiGustavo/create-pull-request@v3
      #   with:
      #     branch: ${{ steps.extract_branch.outputs.branch }}
      #     commit-message: PR Feature ${{ steps.extract_branch.outputs.branch }}
          
