name: Create PR from feature branches
on:
  push:
    branches:
      - 'feature/**'
      - develop
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: | 
          echo "##[set-output name=feature_branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/feature/})"
        id: extract_branch
      - name: Test
        run: | 
          echo "${{ steps.extract_branch.outputs.feature_branch }}"
          echo "${{ steps.extract_branch.outputs.branch }}"

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch
      # - uses: actions/checkout@v2
      #   with:
      #     ref: develop
      # - name: Reset feature branch
      #   run: |
      #     git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
      #     git reset --hard ${{ steps.extract_branch.outputs.branch }}
      # - name: Create Pull Request
      #   uses: CalefiGustavo/create-pull-request@v3
      #   with:
      #     branch: ${{ steps.extract_branch.outputs.branch }}
      #     commit-message: PR Feature ${{ steps.extract_branch.outputs.branch }}
          
