name: Create PR from feature branches
on:
  push:
    branches:
      - 'feature/**'
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Reset feature branch
        run: |
          git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
          git reset --hard ${{ steps.extract_branch.outputs.branch }}
      - name: Create Pull Request
        uses: CalefiGustavo/create-pull-request@v3
        with:
          branch: pr_${{ steps.extract_branch.outputs.branch }}_main
